### ISSUE TITLE
Vorzeichen vergessen

### ISSUE THREAD

**Issue by joseeelig** [onecalfman/thermo#2]
Es müsste 10^{-3} sein:

`mm^3 	\quad& 10^{-9}\quad &&\quad 10^{-6}\quad &&\quad 10^{3}\quad &&\quad 1\quad \quad \\`

https://github.com/onecalfman/thermo/blob/4eeef64a677ddc5851ee247f031411bc3134ef72/thermo.tex#L2945

**Comment by onecalfman** [comment]
fixed with [commit](https://github.com/onecalfman/thermo/commit/96cec2f874734dc93270ee60aa4d512f84888bf3)
